Implement Gateway
CS3219-AY2324S1/ay2324s1-course-assessment-g11 pull request #49
Opened 2023-09-28 08:54 UTC by yhtMinceraft1010X

2023-09-28 19:04 UTC, chunweii requested changes
Thanks for creating the gateway!

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/logging/logging.ts
Is there any reason why we should separate logging from the rest of the code?

2023-09-28 19:04 UTC, chunweii commented on event_types/event_definitions.ts
I am still not very certain of the use of web sockets and events for the gateway. Why would a simple HTTP API call not work? Using web sockets could be appropriate for collaboration service, but not this, in my opinion.

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/app.ts
> +//const port = process.env.PORT;
```suggestion
const port = process.env.PORT || 4000;
```

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/auth/auth.ts
> +      const idToken = req.get("User-Id-Token");
Can we put "User-Id-Token" in a constant?

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/auth/auth.ts
> +const redirectLink = "http://localhost:3000";
Not sure if we should hard-code localhost here. Eventually, when the app is deployed, we will not be hosting it on localhost.

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/auth/auth.ts
> +            console.log("Passing to next function!")
Remove such logging statements. It might be good for debugging but should not be committed.

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/auth/firebase.ts
> +  // });
Remove comments (and all others below)

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/auth/firebase.ts
> +      }
```suggestion
      return uid === paramUid;
```

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/auth/firebase.ts
> +      }
```suggestion
      return !!claims.admin
```

2023-09-28 19:04 UTC, chunweii commented on services/gateway/src/proxied_routes/proxied_routes.ts
> +export const proxied_routes = [
It'll be nice to define a type for each object in this array

2023-09-29 07:12 UTC, yhtMinceraft1010X commented on event_types/event_definitions.ts
One of my considerations for using events was that if a user chooses to delete themselves from the application, the following should happen:
- User's data on the user-service gets deleted
- User gets kicked out of any existing match attempts/collaboration sessions.

2023-09-30 14:35 UTC, yhtMinceraft1010X commented on event_types/event_definitions.ts
Will fix in #54

2023-09-30 14:49 UTC, chunweii approved these changes

2023-09-30 14:49 UTC, merged